name: infinite_search
description: "A simple Proof of Concept of a listing feature with infinite
  scrolling, filtering and search"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: 3.22.1

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
